### ISSUE TITLE
Replace javax.inject with jakarta.inject

### ISSUE THREAD

**Issue by gdany95** [eclipse-nattable/nattable#91]
Eclipse version starting with  2024-03 (4.31.0) dropped support for javax.inject package. It needs to be replaced with jakarta.inject. org.eclipse.nebula.widgets.nattable.extension.e4 still has a dependency to javax.inject so it cannot be used with the new eclipse version.

Provided a patch for these changes:
[nattable.patch](https://github.com/user-attachments/files/15784930/nattable.patch)

**Comment by fipro78** [comment]
Thanks for the report and the patch. But I do not agree completely.

1. The statement _Eclipse version starting with 2024-03 (4.31.0) dropped support for javax.inject package_ is not correct. From 4.30 the Jakarta annotations are supported and it is recommended to migrate. There is a deprecation period of at least two years (see [Eclipse Project 4.30 New and Noteworthy - Support for Jakarta Annotations by Eclipse E4](https://eclipse.dev/eclipse/news/4.30/platform.php#support-jakarta-annotations)). So while I agree that we should migrate, there is no pressure. And I also need to consider users of NatTable that are not yet able to switch to the newest Eclipse version.
2. As a GitHub project we do not accept patch files attached to an issue. Please follow the GitHub process and create a pull request. But because of the above reason I am not willing to merge it soon.

**Comment by gdany95** [comment]
Indeed it seems that adding jakarta.inject.jakarta.inject-api version="1.0.5" to the target platform seems to make it work. A bit misleading as I was searching for a javax plugin, not jakarta.

Anyway, adding a pull request now seems unnecessary, since it won't be merged in the near future, and the change is a two-liner. Closing the issues for now. Thank you!
